### ISSUE TITLE
Ensure GitHub OAuth WebFlow works with 2-factor authentication

### ISSUE THREAD

**Issue by ALRubinger** [redhat-developer-tooling/katapult#26]

**Comment by ALRubinger** [comment]
The current tests work with accounts that don't have 2-factor auth enabled.  I'm not certain how we automate a test that depends on getting an email or TXT message with an auth code, but we do need to be reasonably certain our stuff works with these types of accounts before we launch.

**Comment by starksm64** [comment]
So I tested this out by enabling two factor auth on my account and chose the sms option for the code. Now every time the test runs I get an authorization code sent to my phone, and the test fails because there is an extra page for the authorization code form.

All we can do is to create an optional test that prompts for the code so that test can get the user logged in. It does not look like anything on our side will have to change as all that changes is that the user has an extra step to get logged in.

**Comment by ALRubinger** [comment]
Closing this out; the tests on CI will work against an account that does *not* have 2-factor, and my account (that I will test with locally) does, so that's enough for me. :)  Can't be stubbing out some GitHub account with 2-factor auth that then sends an SMS to a Google Voice Number and we programatically have some inflow SMS service to read in the value...just too much :D
